### ISSUE TITLE
Segfault in the operator if the `manifests` repo is missing

### ISSUE THREAD

**Issue by vpavlin** [kubeflow/kfctl#243]
Just hit the following error [1]

The cause seems to be that I did not have a repo named `manifests` in the KFDef.

`kfctl` actually fails with

```
Error: failed to build kfApp from URI kfdef/kfdef_opendatahub_spark_only.1.0.yaml: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error: Repo manifests not listed in KfDef.Status; 
```

Is anyone aware why the name *manifests* is required? 

Can the operator at least not fail, but rather provide a reasonable error?

[1]
```
{"level":"info","ts":1581944513.3395808,"logger":"controller_kfdef","msg":"Reconciling KfDef","Request.Namespace":"kubeflow-spark","Request.Name":"spark-operator"}
{"level":"info","ts":1581944513.3396165,"logger":"controller_kfdef","msg":"Creating a new KubeFlow Deployment","Request.Namespace":"kubeflow-spark","Request.Name":"spark-operator","KubeFlow.Namespace":"kubeflow-spark"}
time="2020-02-17T13:01:53Z" level=info msg="Creating directory /tmp/.cache"
time="2020-02-17T13:01:53Z" level=info msg="Fetching https://github.com/vpavlin/odh-kf-manifests/archive/master.tar.gz to /tmp/.cache/odh-manifests"
time="2020-02-17T13:01:53Z" level=info msg="updating localPath to /tmp/.cache/odh-manifests/odh-kf-manifests-master"
time="2020-02-17T13:01:53Z" level=info msg="Fetch succeeded; LocalPath /tmp/.cache/odh-manifests/odh-kf-manifests-master"
time="2020-02-17T13:01:53Z" level=info msg="Repo manifests not listed in KfDef.Status; Resync'ing cache"
time="2020-02-17T13:01:53Z" level=info msg="/tmp/.cache/odh-manifests exists; not resyncing "
{"level":"info","ts":1581944513.4623666,"logger":"controller_kfdef","msg":"failed to build kfApp from URI ","Request.Namespace":"kubeflow-spark","Request.Name":"spark-operator","/tmp/config.yaml":null}
E0217 13:01:53.462589       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1565 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1b50fa0, 0x314c710)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1b50fa0, 0x314c710)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/kfctl/v3/pkg/controller/kfdef.kfApply(0xc000170a80, 0x21b6800, 0xc0074e1820, 0x27, 0xc000229c58)
	kfctl/pkg/controller/kfdef/kfdef_controller.go:228 +0x1fa
github.com/kubeflow/kfctl/v3/pkg/controller/kfdef.(*ReconcileKfDef).Reconcile(0xc000965960, 0xc000df85c0, 0xe, 0xc000df85a0, 0xe, 0xc000ad5cd8, 0xc0074a8870, 0xc001094368, 0x2163d40)
	kfctl/pkg/controller/kfdef/kfdef_controller.go:208 +0xae7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000105c20, 0x1be2f00, 0xc000eba080, 0x3171600)
	kfctl/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000105c20, 0xc000dbc100)
	kfctl/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000105c20)
	kfctl/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0074b31c0)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0074b31c0, 0x3b9aca00, 0x0, 0x1, 0xc0000b8180)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0074b31c0, 0x3b9aca00, 0xc0000b8180)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	kfctl/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18759aa]

goroutine 1565 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1b50fa0, 0x314c710)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/kfctl/v3/pkg/controller/kfdef.kfApply(0xc000170a80, 0x21b6800, 0xc0074e1820, 0x27, 0xc000229c58)
	kfctl/pkg/controller/kfdef/kfdef_controller.go:228 +0x1fa
github.com/kubeflow/kfctl/v3/pkg/controller/kfdef.(*ReconcileKfDef).Reconcile(0xc000965960, 0xc000df85c0, 0xe, 0xc000df85a0, 0xe, 0xc000ad5cd8, 0xc0074a8870, 0xc001094368, 0x2163d40)
	kfctl/pkg/controller/kfdef/kfdef_controller.go:208 +0xae7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000105c20, 0x1be2f00, 0xc000eba080, 0x3171600)
	kfctl/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000105c20, 0xc000dbc100)
	kfctl/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000105c20)
	kfctl/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0074b31c0)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0074b31c0, 0x3b9aca00, 0x0, 0x1, 0xc0000b8180)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0074b31c0, 0x3b9aca00, 0xc0000b8180)
	kfctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	kfctl/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32e
```

**Comment by anishasthana** [comment]
I ran into the same issue when I had a kfdef without `manifests` defined.
